### ISSUE TITLE
Min/Max length do not exist

### ISSUE THREAD

**Issue by 22bai70785** [rohitnirban/secure-short-id#1]
## Issue Description
This package does not contain any min/max length which may create problems

## Steps to Reproduce

1. Install this package
2. Import the package
`const generateShortId = require('ssid');`
3. Generate a new ssid by giving its length for eg: 100000
`const customLengthShortId = generateShortId(100000);`

## Expected Behavior
It should give `maximum limit exceed` or `minimum limit can not be less than 4`.

## Actual Behavior
It generates ssid of any size as user wants

## Environment
- Operating System: Windows
- Node.js version: 20
- npm package version: 10

**Comment by coder-abdo** [comment]
Hi,
is this issue still open?

**Comment by rohitnirban** [comment]
> Hi, is this issue still open?

It is closed now, but you can create new issue if you have any
